const CONSTANTS = {
    COLOR_SCREEN_BACKGROUND: "#E2E6EA",
    COLOR_YELLOW: '#FFD42B',
    COLOR_DARK_GREY: '#3E4A59',
    COLOR_LIGHT_GREY: '#9C9C9C',
    COLOR_BLACK: "#000",
    COLOR_WHITE: "#FFF",
    COLOR_GREY: "#BFBFBF",
    COLOR_LABEL:"#8D91A2",
    COLOR_ORANGE:"#FF8942"
};

export default CONSTANTS;