const CONSTANTS = {
    PRIMARY_COLOR: "#FF8B43",
    COLOR_HEADING: "#42436A",
    COLOR_SCREEN_BACKGROUND: "#EDEEF2",
    COLOR_YELLOW: '#FFD42B',
    COLOR_DARK_GREY: '#3E4A59',
    COLOR_LIGHT_GREY: '#9C9C9C',
    COLOR_BLACK: "#000",
    COLOR_WHITE: "#FFF",
    COLOR_GREY: "#BFBFBF",
    COLOR_LABEL:"#8D91A2",
    COLOR_ORANGE:"#FF8942",
    COLOR_LIGHT_GREEN:"#DBFFC5",
    COLOR_LIGHT_YELLOW:"#FFD73C"
};

export default CONSTANTS;